### ISSUE TITLE
Overlay of VOTable catalog files on top of cubes

### ISSUE THREAD

**Issue by veggiesaurus** [idia-astro/iDaVIE#80]
Overlay of generic VOTable catalogs (including WCS transformations) over cubes.

Catalog entries should be visible as either points (no bounding box or radius specified) or boxes (in which case, we also need size information from the catalog)

**Comment by paoloserra** [comment]
Apologies for commenting on this one after such a long time. I was wondering whether, after loading an XML catalogue, I'm supposed to see the source ID when I point inside the bounding box of a source.

That's what happens with sources from a FITS mask, but it does not seem to happen with sources from an XML catalogue. Am I doing something wrong, or is this feature not there?

Thanks!

**Comment by CosmicElysium** [comment]
> Apologies for commenting on this one after such a long time. I was wondering whether, after loading an XML catalogue, I'm supposed to see the source ID when I point inside the bounding box of a source.
> 
> That's what happens with sources from a FITS mask, but it does not seem to happen with sources from an XML catalogue. Am I doing something wrong, or is this feature not there?
> 
> Thanks!

Hi @paoloserra . The cursor info (the text on the primary controller) will only give the source number for masked sources. To get the source number for .xml votables, you can set the ID property when loading the .xml catalog in the SOURCES tab to the relevant column. This will then be displayed in the Source Window and also the Info box when the source is selected.

**Comment by CosmicElysium** [comment]
Actually, we should probably clarify with the label in the cursor info. Currently it reads "Source #" when it should probably be "Mask Source #"

**Comment by paoloserra** [comment]
OK, so no source ID from the cursor info when loading just an XML catalogue? Is it something you could consider implementing in the short term, or does it require major work?

**Comment by paoloserra** [comment]
BTW the case for this is the following. We are looking at cosmological simulations. We have a simulation spatial cube (3 spatial coordinates) and the corresponding catalogue of objects (dark matter halos). We want to identify objects with an interesting 3D morphology in VR, and immediately read their ID (dark matter halo ID). Once we have the ID we will go back to the simulations and do some time rewinding centred on the object of interest. So it is important that we point to an object we like and see its ID right away.

**Comment by CosmicElysium** [comment]
It should be straightforward to implement. We should just be more explicit about what the cursor is hovering over. This is the current situation:
![image](https://github.com/user-attachments/assets/dd2f66d0-14c6-4c9c-8d27-06c16c46e027)

So instead of having just 
`Source:`
at the bottom, it would be something like:
`Mask Source:`
`Box Source:`

The weird thing might be for masked sources, it would show the same source number, the Box Source when the cursor is inside the mask source box outline and the Mask Source when the cursor is hovering over the actual masked voxels. But I think this would be the most straightforward solution still.

**Comment by paoloserra** [comment]
Or maybe you show both numbers? Great to know it's an easy thing to implement!

**Comment by CosmicElysium** [comment]
Yeah it would show both. For example, the cursor inside a masked region may show:
`Mask Source: 5`
`Box Source: 5`

But in the awkward zone where the controller cursor is within the calculated outline box but not touching a masked voxel, it would just show:
`Box Source: 5`

So we would just need to be explicit in the documentation about this unique situation to avoid confusion.

**Comment by CosmicElysium** [comment]
@paoloserra , I made a new issue for this. Please add anything if I missed it.
https://github.com/idia-astro/iDaVIE/issues/414
